#!/bin/sh
set -e

NAME="$(basename "$(dirname "$(pwd)")")"
LOG_DIR="/var/log/runit/$NAME"
LOG_GROUP=adm
LOG_USER=nobody
SUPERVISE_DIR="/var/run/runit/supervise/${NAME}.log"

mkdir -p "$SUPERVISE_DIR" && chmod 700 "$SUPERVISE_DIR"
[ ! -h supervise ] && rm -rf supervise && ln -s "$SUPERVISE_DIR" supervise
mkdir -p "$LOG_DIR" && chmod 750 "$LOG_DIR"
chown -R "$LOG_USER":"$LOG_GROUP" "$LOG_DIR"

exec chpst -u "$LOG_USER" svlogd -tt "$LOG_DIR"
