services:
  graphql-engine:
    image: hasura/graphql-engine:v2.46.0
    ports:
      - 8080
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_GRAPHQL_METADATA_DATABASE_URL:-postgres://${HASURA_POSTGRES_USER:-${POSTGRES_USER:-postgres}}:${HASURA_POSTGRES_PASSWORD:-${POSTGRES_PASSWORD:-postgres}}@postgres:5432/${HASURA_POSTGRES_DB:-${POSTGRES_DB:-postgres}}}
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: ${HASURA_PG_DATABASE_URL:-postgres://${HASURA_POSTGRES_USER:-${POSTGRES_USER:-postgres}}:${HASURA_POSTGRES_PASSWORD:-${POSTGRES_PASSWORD:-postgres}}@postgres:5432/${HASURA_POSTGRES_DB:-${POSTGRES_DB:-postgres}}}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE:-true} # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE:-true}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES:-startup, http-log, webhook-log, websocket-log, query-log}
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: ${HASURA_GRAPHQL_CONSOLE_ASSETS_DIR:-/srv/console-assets}
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-myadminsecretkey}
    labels:
    - SERVICE_8080_CHECK_HTTP=/
    - SERVICE_8080_NAME=${COMPOSE_SERVICE_NAME}-graphql-engine-8080
    - SERVICE_8080_TAGS=${HASURA_GRAPHQL_ENGINE_SERVICE_8080_TAGS:-urlprefix-hasura.localhost/*}
    networks:
    - private
