version: '3.6'

services:
  prometheus:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/prometheus/prometheus
      - BLACKBOX_PRIMARY_TARGETS=${PROMETHEUS_BLACKBOX_PRIMARY_TARGETS}
      - BLACKBOX_SECONDARY_TARGETS=${PROMETHEUS_BLACKBOX_SECONDARY_TARGETS}
      context: ../..
      dockerfile: docker/prometheus/prometheus/Dockerfile
    image: ${DOCKER_REPOSITORY}/prometheus:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9090_CHECK_TCP=true
    - SERVICE_9090_NAME=${COMPOSE_SERVICE_NAME}-prometheus-9090
    - SERVICE_9090_TAGS=${PROMETHEUS_SERVICE_9090_TAGS}
    networks:
    - private
    - public
    ports:
    - 9090
    restart: always
    volumes:
    - prometheus:/prometheus

volumes:
  prometheus:
