ENV_VARS                                  += PROMETHEUS_BLACKBOX_PRIMARY_TARGETS PROMETHEUS_BLACKBOX_SECONDARY_TARGETS PROMETHEUS_SERVICE_9090_TAGS
PROMETHEUS_BLACKBOX_PRIMARY_TARGETS       ?= $(patsubst %,https://%,$(DOMAIN))
PROMETHEUS_BLACKBOX_SECONDARY_TARGETS     ?= $(patsubst %,https://%,$(APP_URIS))
PROMETHEUS_SERVICE_9090_NAME              ?= prometheus
PROMETHEUS_SERVICE_9090_TAGS              ?= $(call tagprefix,prometheus,9090)
