version: '3.6'

services:
  portainer:
    image: portainer/portainer:latest
    labels:
    - SERVICE_8000_IGNORE=true
    - SERVICE_9000_CHECK_HTTP=/
    - SERVICE_9000_NAME=${COMPOSE_SERVICE_NAME}-portainer-9000
    - SERVICE_9000_TAGS=${PORTAINER_SERVICE_9000_TAGS}
    networks:
    - public
    ports:
    - 8000
    - 9000
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data

volumes:
  portainer:
