version: '3.6'

services:
  apm-server-oss:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/elastic/apm-server-oss
      context: ../..
      dockerfile: docker/elastic/apm-server-oss/Dockerfile
    image: ${DOCKER_REPOSITORY}/apm-server-oss:${DOCKER_IMAGE_TAG}
    command: -c apm-server.yml --strict.perms=false -e -E output.elasticsearch.hosts=["${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}"] -E output.elasticsearch.protocol=${ELASTICSEARCH_PROTOCOL:-http} -E output.elasticsearch.username=${ELASTICSEARCH_USERNAME} -E output.elasticsearch.password=${ELASTICSEARCH_PASSWORD} -E apm-server.register.ingest.pipeline.enabled=false
    labels:
    - SERVICE_8200_CHECK_HTTP=/
    - SERVICE_8200_NAME=${COMPOSE_SERVICE_NAME}-apm-server-oss-8200
    - SERVICE_8200_TAGS=${APM_SERVER_OSS_SERVICE_8200_TAGS}
    networks:
    - private
    - public
    ports:
    - 8200
    restart: always
