version: '3.6'

services:
  redmine3:
    image: sameersbn/redmine:3.4.12
    environment:
    - DB_ADAPTER=${REDMINE_DB_ADAPTER:-mysql2}
    - DB_HOST=${REDMINE_DB_HOST:-mysql}
    - DB_NAME=${REDMINE3_DB_NAME:-redmine3}
    - DB_USER=${REDMINE3_DB_USER:-redmine3}
    - DB_PASS=${REDMINE3_DB_PASS:-redmine3}
    - REDMINE_SECRET_TOKEN=${REDMINE_SECRET_TOKEN}
    - SMTP_DOMAIN=${REDMINE_SMTP_DOMAIN}
    - SMTP_USER=${REDMINE_SMTP_USER}
    - SMTP_PASS=${REDMINE_SMTP_PASS}
    - TZ=${REDMINE_TZ:-Europe/Paris}
    labels:
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-redmine3-80
    - SERVICE_80_TAGS=${REDMINE3_SERVICE_80_TAGS:-}
    - SERVICE_443_IGNORE=true
    networks:
    - private
    - public
    ports:
    - 80
    restart: always
    volumes:
    - redmine3:/home/redmine/data

volumes:
  redmine3:
