ENV_VARS                                  += NODE_CONSUL_ACL_TOKENS_MASTER NODE_CONSUL_HTTP_TOKEN NODE_CONSUL_SERVICE_8500_TAGS
NODE_CONSUL_ACL_TOKENS_MASTER             ?= 01234567-89ab-cdef-0123-456789abcdef
NODE_CONSUL_HTTP_TOKEN                    ?= $(NODE_CONSUL_ACL_TOKENS_MASTER)
NODE_CONSUL_SERVICE_8500_TAGS             ?= urlprefix-consul.${DOMAIN}/
NODE_CONSUL_UFW_UPDATE                    ?= 8500
