ENV_VARS                                  += NODE_EXPORTER_CADVISOR_SERVICE_8080_TAGS NODE_EXPORTER_NODE_SERVICE_9100_TAGS
NODE_EXPORTER_CADVISOR_SERVICE_8080_TAGS  ?= urlprefix-cadvisor-exporter.${DOMAIN}/
NODE_EXPORTER_NODE_SERVICE_9100_TAGS      ?= urlprefix-node-exporter.${DOMAIN}/
