version: '3.6'

services:
  myos:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/myos
      - GID=${GID}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - IPFS_VERSION=${IPFS_VERSION}
      - UID=${UID}
      - USER=${USER}
      - SSH_BASTION_HOSTNAME=${SSH_BASTION_HOSTNAME:-}
      - SSH_BASTION_USERNAME=${SSH_BASTION_USERNAME:-}
      - SSH_PUBLIC_HOSTS=${SSH_PUBLIC_HOSTS:-}
      - SSH_PRIVATE_IP_RANGE=${SSH_PRIVATE_IP_RANGE:-}
      context: ../..
      dockerfile: docker/myos/Dockerfile
    container_name: ${USER_DOCKER_NAME}
    environment:
    - ENV=${ENV}
    - RC_00_SOURCE=${USER_RC_SOURCE:-/etc/profile.d/rc_functions.sh}
    - RC_01_PS1_SET=${USER_RC_PS1_SET:-true}
    - RC_02_PROMPT_SET=${USER_RC_PROMPT_SET:-true}
    - RC_03_SSH_ADD=${USER_RC_SSH_ADD:-true}
    - RC_04_TMUX_ATTACH=${USER_RC_TMUX_ATTACH:-false}
    - RC_05_SCREEN_ATTACH=${USER_RC_SCREEN_ATTACH:-true}
    - SHELL=${DOCKER_SHELL}
    image: ${USER_DOCKER_IMAGE}
    networks:
    - private
    restart: always
    user: ${UID}:${GID}
    volumes:
    - ${HOME}:${HOME}:cached
    - sources:${MONOREPO_DIR}:cached
    - user:/tmp/ssh-agent
    working_dir: ${MONOREPO_DIR}

volumes:
  sources:
    driver: local
    driver_opts:
      type: none
      device: ${MONOREPO_DIR}
      o: bind
    name: ${USER}_sources
  user:
    external: true
    name: ${USER_DOCKER_VOLUME}

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
