#!/bin/bash
# shellcheck source=/dev/null disable=SC2046
### BEGIN INIT INFO
# Provides: myos
# Required-Start: docker
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: MYOS system calls
### END INIT INFO

# check system config
[ -r /etc/default/myos ] && . /etc/default/myos 2>/dev/null
type make >/dev/null 2>&1 && [ -d "${MYOS}" ] || exit 1

case "$1" in
  *)
    IFS=$'\n'; cd "${MYOS}"; exec env $(cat /etc/default/myos ~/.myos 2>/dev/null) make "$@"
esac
