version: '3.6'

services:
  logagent:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/sematext/logagent
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      context: ../..
      dockerfile: docker/sematext/logagent/Dockerfile
    image: ${DOCKER_REPOSITORY}/logagent:${DOCKER_IMAGE_TAG}
    environment:
    - LOGAGENT_ARGS=-u 514 --docker /tmp/docker.sock --dockerEvents
    - LOGS_RECEIVER_URL=${ELASTICSEARCH_PROTOCOL}://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    - LOGS_TOKEN=logs-YYYY.MM.DD
    networks:
    - private
    ports:
    - 514
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
