version: '3.6'

services:
  autoheal:
    container_name: ${HOST_COMPOSE_PROJECT_NAME}-autoheal
    environment:
    - AUTOHEAL_CONTAINER_LABEL=all
    image: willfarrell/autoheal:latest
    restart: always
    volumes:
    - ${DOCKER_SOCKET_LOCATION}:/var/run/docker.sock
