ENV_VARS                                  += HOST_CONSUL_ACL_TOKENS_MASTER HOST_CONSUL_HTTP_TOKEN HOST_CONSUL_SERVICE_8500_TAGS
HOST_CONSUL_ACL_TOKENS_MASTER             ?= 01234567-89ab-cdef-0123-456789abcdef
HOST_CONSUL_HTTP_TOKEN                    ?= $(HOST_CONSUL_ACL_TOKENS_MASTER)
HOST_CONSUL_SERVICE_URIS                  ?= $(patsubst %,consul.%,$(APP_URIS))
HOST_CONSUL_SERVICE_8500_TAGS             ?= $(call urlprefix,,$(HOST_CONSUL_SERVICE_8500_URIS))
HOST_CONSUL_SERVICE_8500_URIS             ?= $(HOST_CONSUL_SERVICE_URIS)
HOST_CONSUL_UFW_UPDATE                    ?= 8500
