ENV_VARS                                  += HOST_EXPORTER_CADVISOR_SERVICE_8080_TAGS HOST_EXPORTER_NODE_SERVICE_9100_TAGS
HOST_EXPORTER_CADVISOR_SERVICE_URIS       ?= $(patsubst %,cadvisor-exporter.%,$(APP_URIS))
HOST_EXPORTER_CADVISOR_SERVICE_8080_TAGS  ?= $(call urlprefix,,$(HOST_EXPORTER_CADVISOR_SERVICE_8080_URIS))
HOST_EXPORTER_CADVISOR_SERVICE_8080_URIS  ?= $(HOST_EXPORTER_CADVISOR_SERVICE_URIS)
HOST_EXPORTER_NODE_SERVICE_URIS           ?= $(patsubst %,node-exporter.%,$(APP_URIS))
HOST_EXPORTER_NODE_SERVICE_9100_TAGS      ?= $(call urlprefix,,$(HOST_EXPORTER_NODE_SERVICE_9100_URIS))
HOST_EXPORTER_NODE_SERVICE_9100_URIS      ?= $(HOST_EXPORTER_NODE_SERVICE_URIS)
