ENV_VARS                                  += HOST_EXPORTER_CADVISOR_SERVICE_8080_TAGS HOST_EXPORTER_HOST_SERVICE_9100_TAGS
HOST_EXPORTER_CADVISOR_SERVICE_8080_TAGS  ?= urlprefix-cadvisor-exporter.${DOMAIN}/
HOST_EXPORTER_HOST_SERVICE_9100_TAGS      ?= urlprefix-node-exporter.${DOMAIN}/
