version: '3.6'

services:
  ipfs:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/ipfs
      - GID=${HOST_GID}
      - IPFS_VERSION=${IPFS_VERSION}
      - UID=${HOST_UID}
      context: ../..
      dockerfile: docker/ipfs/Dockerfile
    command: daemon --agent-version-suffix=${HOST_COMPOSE_PROJECT_NAME} ${HOST_IPFS_DAEMON_ARGS:---migrate}
    container_name: ${HOST_COMPOSE_PROJECT_NAME}-ipfs
    cpus: 0.5
    environment:
    - IPFS_ADDRESSES_API=${HOST_IPFS_ADDRESSES_API:-}
    - IPFS_ADDRESSES_API_DOMAIN=${HOST_IPFS_ADDRESSES_API_DOMAIN:-${DOCKER_NETWORK_PUBLIC}}
    - IPFS_ADDRESSES_API_INET4=${HOST_IPFS_ADDRESSES_API_INET4:-}
    - IPFS_ADDRESSES_API_PORT=${HOST_IPFS_ADDRESSES_API_PORT:-}
    - IPFS_ADDRESSES_GATEWAY=${HOST_IPFS_ADDRESSES_GATEWAY:-}
    - IPFS_ADDRESSES_GATEWAY_DOMAIN=${HOST_IPFS_ADDRESSES_GATEWAY_DOMAIN:-}
    - IPFS_ADDRESSES_GATEWAY_INET4=${HOST_IPFS_ADDRESSES_GATEWAY_INET4:-0.0.0.0}
    - IPFS_ADDRESSES_GATEWAY_PORT=${HOST_IPFS_ADDRESSES_GATEWAY_PORT:-}
    - IPFS_ADDRESSES_NOANNOUNCE=${HOST_IPFS_ADDRESSES_NOANNOUNCE:-}
    - IPFS_API_HTTPHEADERS=${HOST_IPFS_API_HTTPHEADERS:-}
    - IPFS_API_HTTPHEADERS_ACA_CREDENTIALS=${HOST_IPFS_API_HTTPHEADERS_ACA_CREDENTIALS:-["true"]}
    - IPFS_API_HTTPHEADERS_ACA_HEADERS=${HOST_IPFS_API_HTTPHEADERS_ACA_HEADERS:-["X-Requested-With", "Range", "User-Agent"]}
    - IPFS_API_HTTPHEADERS_ACA_METHODS=${HOST_IPFS_API_HTTPHEADERS_ACA_METHODS:-["OPTIONS", "POST"]}
    - IPFS_API_HTTPHEADERS_ACA_ORIGIN=${HOST_IPFS_API_HTTPHEADERS_ACA_ORIGIN:-}
    - IPFS_BOOTSTRAP=${HOST_IPFS_BOOTSTRAP:-}
    - IPFS_DATASTORE_GCPERIOD=${HOST_IPFS_DATASTORE_GCPERIOD:-}
    - IPFS_DISK_USAGE_PERCENT=${HOST_IPFS_DISK_USAGE_PERCENT:-}
    - IPFS_EXPERIMENTAL_ACCELERATEDDHTCLIENT=${HOST_IPFS_EXPERIMENTAL_ACCELERATEDDHTCLIENT:-true}
    - IPFS_EXPERIMENTAL_FILESTOREENABLED=${HOST_IPFS_EXPERIMENTAL_FILESTOREENABLED:-}
    - IPFS_EXPERIMENTAL_GRAPHSYNCENABLED=${HOST_IPFS_EXPERIMENTAL_GRAPHSYNCENABLED:-}
    - IPFS_EXPERIMENTAL_LIBP2PSTREAMMOUNTING=${HOST_IPFS_EXPERIMENTAL_LIBP2PSTREAMMOUNTING:-true}
    - IPFS_EXPERIMENTAL_P2PHTTPPROXY=${HOST_IPFS_EXPERIMENTAL_P2PHTTPPROXY:-true}
    - IPFS_EXPERIMENTAL_STRATEGICPROVIDING=${HOST_IPFS_EXPERIMENTAL_STRATEGICPROVIDING:-}
    - IPFS_EXPERIMENTAL_URLSTOREENABLED=${HOST_IPFS_EXPERIMENTAL_URLSTOREENABLED:-}
    - IPFS_IDENTITY_PEERID=${HOST_IPFS_IDENTITY_PEERID:-}
    - IPFS_IDENTITY_PRIVKEY=${HOST_IPFS_IDENTITY_PRIVKEY:-}
    - IPFS_IPNS_REPUBLISHPERIOD=${HOST_IPFS_IPNS_REPUBLISHPERIOD:-}
    - IPFS_IPNS_RECORDLIFETIME=${HOST_IPFS_IPNS_RECORDLIFETIME:-}
    - IPFS_IPNS_USEPUBSUB=${HOST_IPFS_IPNS_USEPUBSUB:-true}
    - IPFS_LOGGING=${HOST_IPFS_LOGGING:-error}
    - IPFS_NETWORK=${HOST_IPFS_NETWORK:-public}
    - IPFS_PATH=${HOST_IPFS_PATH:-/data/ipfs}
    - IPFS_PROFILE=${HOST_IPFS_PROFILE:-${IPFS_PROFILE}}
    - IPFS_PUBSUB_ENABLE=${HOST_IPFS_PUBSUB_ENABLE:-true}
    - IPFS_PUBSUB_ROUTER=${HOST_IPFS_PUBSUB_ROUTER:-gossipsub}
    - IPFS_ROUTING_TYPE=${HOST_IPFS_ROUTING_TYPE:-dht}
    - IPFS_REPROVIDER_INTERVAL=${HOST_IPFS_REPROVIDER_INTERVAL:-}
    - IPFS_REPROVIDER_STRATEGY=${HOST_IPFS_REPROVIDER_STRATEGY:-roots}
    - IPFS_SWARM_CONNMGR_HIGHWATER=${HOST_IPFS_SWARM_CONNMGR_HIGHWATER:-}
    - IPFS_SWARM_CONNMGR_LOWWATER=${HOST_IPFS_SWARM_CONNMGR_LOWWATER:-}
    - IPFS_SWARM_CONNMGR_TYPE=${HOST_IPFS_SWARM_CONNMGR_TYPE:-}
    - IPFS_SWARM_DISABLENATPORTMAP=${HOST_IPFS_SWARM_DISABLENATPORTMAP:-}
    - IPFS_SWARM_ENABLEHOLEPUNCHING=${HOST_IPFS_SWARM_ENABLEHOLEPUNCHING:-}
    - IPFS_SWARM_KEY=${HOST_IPFS_SWARM_KEY:-}
    - IPFS_SWARM_RELAYCLIENT_ENABLED=${HOST_IPFS_SWARM_RELAYCLIENT_ENABLED:-}
    - IPFS_SWARM_RELAYSERVICE_ENABLED=${HOST_IPFS_SWARM_RELAYSERVICE_ENABLED:-}
    - IPFS_SWARM_TRANSPORTS_NETWORK_RELAY=${HOST_IPFS_SWARM_TRANSPORTS_NETWORK_RELAY:-}
    image: ${HOST_DOCKER_REPOSITORY}/ipfs:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_4001_CHECK_TCP=true
    - SERVICE_4001_NAME=${HOST_COMPOSE_SERVICE_NAME}-ipfs-4001
    - SERVICE_5001_CHECK_HTTP=${HOST_IPFS_SERVICE_5001_CHECK_HTTP:-/api/v0/diag/sys}
    - SERVICE_5001_CHECK_HTTP_METHOD=${HOST_IPFS_SERVICE_5001_CHECK_HTTP_METHOD:-POST}
    - SERVICE_5001_NAME=${HOST_COMPOSE_SERVICE_NAME}-ipfs-5001
    - SERVICE_5001_TAGS=${HOST_IPFS_SERVICE_5001_TAGS:-}
    - SERVICE_8080_CHECK_HTTP=${HOST_IPFS_SERVICE_8080_CHECK_HTTP:-/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme}
    - SERVICE_8080_NAME=${HOST_COMPOSE_SERVICE_NAME}-ipfs-8080
    - SERVICE_8080_TAGS=${HOST_IPFS_SERVICE_8080_TAGS:-}
    - SERVICE_8081_IGNORE=true
    networks:
    - public
    ports:
    - 4001:4001/tcp
    - 4001:4001/udp
    - 5001:5001/tcp
    - 8080:8080/tcp
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - home:/home:delegated
    - ipfs:/data/ipfs:delegated

volumes:
  home:
  ipfs:

networks:
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
