version: '3.6'

services:
  389ds:
    build:
      args:
      - BUILD_VERSION=${HOST_389DS_VERSION}
      - DOCKER_BUILD_DIR=docker/389ds
      context: ../..
      dockerfile: docker/389ds/Dockerfile
    container_name: ${HOST_COMPOSE_PROJECT_NAME}-389ds
    hostname: ${HOSTNAME}
    image: ${HOST_DOCKER_REPOSITORY}/389ds:${DOCKER_IMAGE_TAG}
    network_mode: host
    restart: always

