version: '3.6'

services:
  nginx:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/nginx
      context: ../..
      dockerfile: docker/nginx/Dockerfile
    domainname: ${DOMAINNAME}
    environment:
    - DEFAULT=${HOST_NGINX_DEFAULT:-default}
    - DEFAULT_HOST=${HOST_NGINX_DEFAULT_HOST:-}
    - DEFAULT_LOCATION=${HOST_NGINX_DEFAULT_LOCATION:-}
    - DEFAULT_LOCATION_PHP=${HOST_NGINX_DEFAULT_LOCATION_PHP:-}
    - DEFAULT_LOCATION_IPFS=${HOST_NGINX_DEFAULT_LOCATION_IPFS:-}
    - LETSENCRYPT_HOST=${HOST_NGINX_LETSENCRYPT_HOST:-${HOST_NGINX_VIRTUAL_HOST:-}}
    - LETSENCRYPT_EMAIL=${HOST_NGINX_LETSENCRYPT_EMAIL:-${HOST_ACME_DEFAULT_EMAIL:-${DEFAULT_EMAIL:-${MAIL:-nginx@localhost}}}}
    - LETSENCRYPT_SINGLE_DOMAIN_CERTS=${HOST_NGINX_LETSENCRYPT_SINGLE_DOMAIN_CERTS:-true}
    - LETSENCRYPT_TEST=${HOST_NGINX_LETSENCRYPT_TEST:-${LETSENCRYPT_TEST:-}}
    - SSL_POLICY=${HOST_NGINX_SSL_POLICY:-Mozilla-Modern}
    - VIRTUAL_HOST=${HOST_NGINX_VIRTUAL_HOST:-localhost}
    - VIRTUAL_PATH=${HOST_NGINX_VIRTUAL_PATH:-/}
    - VIRTUAL_PROTO=${HOST_NGINX_VIRTUAL_PROTO:-local}
    hostname: ${HOSTNAME}
    image: ${DOCKER_REPOSITORY:-nginx}/nginx:${DOCKER_IMAGE_TAG:-latest}
    labels:
    - SERVICE_80_CHECK_TCP=${HOST_NGINX_SERVICE_80_CHECK_TCP:-true}
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME:-docker}-nginx-80
    - SERVICE_80_TAGS=${HOST_NGINX_SERVICE_80_TAGS:-urlprefix-localhost:80/*}
    - SERVICE_443_CHECK_TCP=${HOST_NGINX_SERVICE_443_CHECK_TCP:-true}
    - SERVICE_443_NAME=${COMPOSE_SERVICE_NAME:-docker}-nginx-443
    - SERVICE_443_TAGS=${HOST_NGINX_SERVICE_443_TAGS:-urlprefix-localhost:443/* proto=https tlsskipverify=true}
    networks:
    - public
    ports:
    - 80
    - 443
    restart: unless-stopped
    volumes:
    - ${DOCKER_SOCKET_LOCATION}:/tmp/docker.sock:ro
    - certs:/etc/nginx/certs
    - html:/usr/share/nginx/html
    - htpasswd:/etc/nginx/htpasswd
    - log:/var/log/nginx
    - vhost:/etc/nginx/vhost.d

volumes:
  certs:
  html:
  htpasswd:
  log:
  vhost:
