version: '3.6'

services:
  php:
    environment:
    - VIRTUAL_HOST=php
    - VIRTUAL_PROTO=fastcgi
    image: php:fpm-alpine
    networks:
    - public
    volumes:
    - www:/var/www

volumes:
  www:

networks:
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
