version: '3.6'

services:
  portainer:
    container_name: ${HOST_COMPOSE_PROJECT_NAME}-portainer
    image: portainer/portainer:latest
    labels:
    - SERVICE_8000_IGNORE=true
    - SERVICE_9000_CHECK_HTTP=/
    - SERVICE_9000_NAME=${HOST_COMPOSE_SERVICE_NAME}-portainer-9000
    - SERVICE_9000_TAGS=${HOST_PORTAINER_SERVICE_9000_TAGS}
    networks:
    - public
    ports:
    - 8000
    - 9000
    restart: always
    volumes:
    - ${DOCKER_SOCKET_LOCATION}:/var/run/docker.sock
    - portainer:/data

volumes:
  portainer:
