version: '3.6'

services:
  registrator:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/registrator
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      context: ../..
      dockerfile: docker/registrator/Dockerfile
    command: -internal -cleanup -deregister always -resync=30 -useIpFromNetwork "${DOCKER_NETWORK_PUBLIC}" -useIpFromLabel SERVICE_ADDRESS consul://consul:8500
    container_name: ${HOST_COMPOSE_PROJECT_NAME}-registrator
    depends_on:
    - consul
    domainname: ${DOMAINNAME}
    environment:
    - CONSUL_HTTP_TOKEN=${HOST_CONSUL_HTTP_TOKEN}
    - GL_DISABLE_VERSION_CHECK=true
    extra_hosts:
    - consul:${DOCKER_INTERNAL_DOCKER_HOST}
    - ${HOSTNAME}.${DOMAINNAME} ${HOSTNAME}:${DOCKER_HOST_INET4}
    hostname: ${HOSTNAME}
    image: ${HOST_DOCKER_REPOSITORY}/registrator:${DOCKER_IMAGE_TAG}
    network_mode: host
    restart: always
    volumes:
    - ${DOCKER_SOCKET_LOCATION}:/tmp/docker.sock
