ENV_VARS                                  += SUPABASE_ADDITIONAL_REDIRECT_URLS SUPABASE_ANON_KEY SUPABASE_JWT_IAT SUPABASE_JWT_EXP SUPABASE_KONG_SERVICE_8000_TAGS SUPABASE_PUBLIC_URL SUPABASE_REALTIME_TENANT SUPABASE_SERVICE_ROLE_KEY SUPABASE_EDGE_RUNTIME_VERSION SUPABASE_KONG_VERSION SUPABASE_POSTGRES_VERSION SUPABASE_VECTOR_VERSION
SUPABASE_ADDITIONAL_REDIRECT_URLS         ?= $(subst $(space),$(comma),$(call url,SUPABASE))
SUPABASE_ANON_KEY                         ?= $(call JWT,,$(SUPABASE_JWT_PAYLOAD_ANON),$(SUPABASE_JWT_SECRET))
SUPABASE_DOCKER_IMAGES                    ?= supabase/edge-runtime:$(SUPABASE_EDGE_RUNTIME_VERSION) kong:$(SUPABASE_KONG_VERSION) supabase/postgres:$(SUPABASE_POSTGRES_VERSION) timberio/vector:$(SUPABASE_VECTOR_VERSION)
SUPABASE_JWT_IAT                          ?= $(MAKE_UNIXTIME_START)
SUPABASE_JWT_EXP                          ?= $(shell echo $$(($(SUPABASE_JWT_IAT)+94608000)))
SUPABASE_JWT_PAYLOAD_ANON                 ?= {\n  "role": "anon",\n  "iss": "supabase",\n  "iat": $(SUPABASE_JWT_IAT),\n  "exp": $(SUPABASE_JWT_EXP)\n}
SUPABASE_JWT_PAYLOAD_SERVICE              ?= {\n  "role": "service_role",\n  "iss": "supabase",\n  "iat": $(SUPABASE_JWT_IAT),\n  "exp": $(SUPABASE_JWT_EXP)\n}
SUPABASE_KONG_SERVICE_8000_TAGS           ?= $(call tagprefix,SUPABASE,8000)
SUPABASE_PUBLIC_URL                       ?= $(SUPABASE_SERVICE_URL)
SUPABASE_REALTIME_TENANT                  ?= realtime-dev
SUPABASE_SERVICE_NAME                     ?= supabase
SUPABASE_SERVICE_ROLE_KEY                 ?= $(call JWT,,$(SUPABASE_JWT_PAYLOAD_SERVICE),$(SUPABASE_JWT_SECRET))
SUPABASE_SERVICE_URIS                     ?= $(call uri,SUPABASE)
SUPABASE_SERVICE_URL                      ?= $(call firstword,$(call url,SUPABASE))
SUPABASE_EDGE_RUNTIME_VERSION             ?= $(shell awk -F: '/image: supabase\/edge-runtime:/ {print $$3}' stack/supabase/docker-compose.yml)
SUPABASE_KONG_VERSION                     ?= $(shell awk -F: '/image: kong:/ {print $$3}' stack/supabase/docker-compose.yml)
SUPABASE_POSTGRES_VERSION                 ?= $(shell awk -F: '/image: supabase\/postgres:/ {print $$3}' stack/supabase/docker-compose.yml)
SUPABASE_VECTOR_VERSION                   ?= $(shell awk -F: '/image: timberio\/vector:/ {print $$3}' stack/supabase/docker-compose.yml)
