#!/bin/sh
set -e

NAME="$(basename "$(pwd)")"
[ "$1" = -1 ] && echo "ERROR: unexpected error"

[ "$1" = 1 ] && echo "ERROR: $NAME config error" \
     && sv d "$NAME" && exit 0

[ "$1" = 2 ] && echo "ERROR: $NAME exit error" \
     && sv d "$NAME" && exit 0

exec /etc/init.d/"$NAME" stop 2>&1
