# This is a minimal docker-compose.yml template for running a Duniter instance
# For more detailed examples, look at docker/compose folder

version: "3.5"

services:

  oracle:
    entrypoint: docker-distance-entrypoint
    environment:
      ORACLE_RPC_URL: "ws://v2s:9944"
      ORACLE_RESULT_DIR: "/var/lib/duniter/chains/${DUNITER_V2S_DUNITER_CHAIN_NAME:-gtest}/distance/"
      ORACLE_EXECUTION_INTERVAL: "1800"
      ORACLE_MAX_DEPTH: "5"
      ORACLE_LOG_LEVEL: "info"
    image: duniter/duniter-v2s-gtest-1100:1000-0.12.0-amd64
    labels:
    - SERVICE_9615_IGNORE=true
    - SERVICE_9944_IGNORE=true
    - SERVICE_30333_IGNORE=true
    networks:
    - private
    restart: always
    volumes:
    - v2s-data:/var/lib/duniter

  ui:
    environment:
    - WS_URL=${DUNITER_UI_WS_URL:-ws://v2s:9944}
    image: duniter/duniter-portal:latest
    labels:
    - SERVICE_80_CHECK_HTTP=${DUNITER_UI_SERVICE_80_CHECK_HTTP:-/}
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-ui-80
    - SERVICE_80_TAGS=${DUNITER_UI_SERVICE_80_TAGS:-urlprefix-gtest.localhost/*}
    networks:
    - private
    ports:
    - 80
    restart: always

  v2s:
    environment:
    - DUNITER_CHAIN_NAME=${DUNITER_V2S_DUNITER_CHAIN_NAME:-gtest}
    - DUNITER_LISTEN_ADDR=${DUNITER_V2S_DUNITER_LISTEN_ADDR:-/ip4/0.0.0.0/tcp/30333/ws}
    - DUNITER_NODE_NAME=${DUNITER_V2S_DUNITER_NODE_NAME:-duniter_gtest_local}
    - DUNITER_PRUNING_PROFILE=${DUNITER_V2S_DUNITER_PRUNING_PROFILE:-default}
    - DUNITER_PUBLIC_ADDR=${DUNITER_V2S_DUNITER_PUBLIC_ADDR:-/dns/duniter.localhost/tcp/30333/ws}
    - DUNITER_PUBLIC_RPC=${DUNITER_V2S_DUNITER_PUBLIC_RPC:-}
    - DUNITER_VALIDATOR=${DUNITER_V2S_DUNITER_VALIDATOR:-false}
    image: duniter/duniter-v2s-gtest-1100:1000-0.12.0-amd64
    labels:
    - SERVICE_9615_CHECK_TCP=true
    - SERVICE_9615_NAME=${COMPOSE_SERVICE_NAME}-v2s-9615
    - SERVICE_9615_TAGS=${DUNITER_V2S_SERVICE_9615_TAGS:-urlprefix-gtest.localhost/metrics/*}
    - SERVICE_9944_CHECK_TCP=true
    - SERVICE_9944_NAME=${COMPOSE_SERVICE_NAME}-v2s-9944
    - SERVICE_9944_TAGS=${DUNITER_V2S_SERVICE_9944_TAGS:-urlprefix-gtest.localhost/ws/*}
    - SERVICE_30333_CHECK_TCP=true
    - SERVICE_30333_NAME=${COMPOSE_SERVICE_NAME}-v2s-30333
    networks:
    - private
    ports:
    # telemetry
    - 9615
    # rpc-ws
    - 9944
    # p2p
    - 30333
    volumes:
    - v2s-data:/var/lib/duniter
    restart: always

volumes:
  v2s-data:
